export const AUTOMATIC_COMPLAINT_ASSIGNMENT = "AUTOMATIC_COMPLAINT_ASSIGNMENT";
export const ASSIGNMENT_ERROR = "ASSIGNMENT_ERROR";
export const RESET_AUTOMATIC_COMPLETE = "RESET_AUTOMATIC_COMPLETE";

export const CLEAR_ERROR = "CLEAR_ERROR";
