export const COMPLAINT_ADD_REQUEST = "COMPLAINT_ADD_REQUEST";
export const COMPLAINT_ADD_SUCCESS = "COMPLAINT_ADD_SUCCESS";
export const COMPLAINT_ADD_FAIL = "COMPLAINT_ADD_FAIL";
export const RESET_COMPLAINT_ADD = "RESET_COMPLAINT_ADD";

export const COMPLAINT_DELETE_REQUEST = "COMPLAINT_DELETE_REQUEST";
export const COMPLAINT_DELETE_SUCCESS = "COMPLAINT_DELETE_SUCCESS";
export const COMPLAINT_DELETE_FAIL = "COMPLAINT_DELETE_FAIL";

export const GET_COMPLAINT_DATA_REQUEST = "GET_COMPLAINT_DATA_REQUEST";
export const GET_COMPLAINT_DATA_SUCCESS = "GET_COMPLAINT_DATA_SUCCESS";
export const GET_COMPLAINT_DATA_FAIL = "GET_COMPLAINT_DATA_FAIL";

export const GET_COMPLAINT_SINGLE_DATA_REQUEST =
  "GET_COMPLAINT_SINGLE_DATA_REQUEST";
export const GET_COMPLAINT_SINGLE_DATA_SUCCESS =
  "GET_COMPLAINT_SINGLE_DATA_SUCCESS";
export const GET_COMPLAINT_SINGLE_DATA_FAIL = "GET_COMPLAINT_SINGLE_DATA_FAIL";

export const COMPLAINT_DELETE_RESET = "COMPLAINT_DELETE_RESET";

export const CLEAR_COMPLAINT_ADD_ERROR = "CLEAR_COMPLAINT_ADD_ERROR";
export const CLEAR_COMPLAINT_DATA_ERROR = "CLEAR_COMPLAINT_DATA_ERROR";
export const CLEAR_COMPLAINT_SINGLE_DATA_ERROR =
  "CLEAR_COMPLAINT_SINGLE_DATA_ERROR";
