export const ELECTRICIAN_REGISTER_REQUEST = "ELECTRICIAN_REGISTER_REQUEST";
export const ELECTRICIAN_REGISTER_SUCCESS = "ELECTRICIAN_REGISTER_SUCCESS";
export const ELECTRICIAN_REGISTER_FAIL = "ELECTRICIAN_REGISTER_FAIL";
export const ELECTRICIAN_REGISTER_RESET = "ELECTRICIAN_REGISTER_RESET";

export const ELECTRICIAN_DELETE_REQUEST = "ELECTRICIAN_DELETE_REQUEST";
export const ELECTRICIAN_DELETE_SUCCESS = "ELECTRICIAN_DELETE_SUCCESS";
export const ELECTRICIAN_DELETE_FAIL = "ELECTRICIAN_DELETE_FAIL";

export const ELECTRICIAN_DELETE_RESET = "ELECTRICIAN_DELETE_RESET";

export const GET_ELECTRICIAN_DATA_REQUEST = "GET_ELECTRICIAN_DATA_REQUEST";
export const GET_ELECTRICIAN_DATA_SUCCESS = "GET_ELECTRICIAN_DATA_SUCCESS";
export const GET_ELECTRICIAN_DATA_FAIL = "GET_ELECTRICIAN_DATA_FAIL";

export const GET_ELECTRICIAN_SINGLE_DATA_REQUEST =
  "GET_ELECTRICIAN_SINGLE_DATA_REQUEST";
export const GET_ELECTRICIAN_SINGLE_DATA_SUCCESS =
  "GET_ELECTRICIAN_SINGLE_DATA_SUCCESS";
export const GET_ELECTRICIAN_SINGLE_DATA_FAIL =
  "GET_ELECTRICIAN_SINGLE_DATA_FAIL";

export const CLEAR_REGISTER_ERROR = "CLEAR_REGISTER_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
