export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGIN_USER_DETAILS_REQUEST = "LOGIN_USER_DETAILS_REQUEST";
export const LOGIN_USER_DETAILS_SUCCESS = "LOGIN_USER_DETAILS_SUCCESS";
export const LOGIN_USER_DETAILS_FAIL = "LOGIN_USER_DETAILS_FAIL";

export const ALL_REGISTERED_USERS_REQUEST = "ALL_REGISTERED_USERS_REQUEST";
export const ALL_REGISTERED_USERS_SUCCESS = "ALL_REGISTERED_USERS_SUCCESS";
export const ALL_REGISTERED_USERS_FAIL = "ALL_REGISTERED_USERS_FAIL";

export const GET_USER_SINGLE_DATA_REQUEST = "GET_USER_SINGLE_DATA_REQUEST";
export const GET_USER_SINGLE_DATA_SUCCESS = "GET_USER_SINGLE_DATA_SUCCESS";
export const GET_USER_SINGLE_DATA_FAIL = "GET_USER_SINGLE_DATA_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_DETAILS = "CLEAR_DETAILS";
