export const RESOLVE_COMPLAINT_REQUEST = "RESOLVE_COMPLAINT_REQUEST";
export const RESOLVE_COMPLAINT_SUCCESS = "RESOLVE_COMPLAINT_SUCCESS";
export const RESOLVE_COMPLAINT_FAILURE = "RESOLVE_COMPLAINT_FAILURE";

export const RESET_RESOLVE_COMPLAINT = "RESET_RESOLVE_COMPLAINT";
